from custom_pec.constants import (
	STAGE_CLOSURE,
	STAGE_COLD,
	STAGE_EVALUATION,
	STAGE_INQUIRY,
	STAGE_PROPOSAL,
	STAGE_QUALIFICATION,
	STAGE_QUERIES,
)

MODULE = "Custom PEC"

YES_NO_REVIEW = "Yes\nNo\nReview Needed"
YES_NO = "Yes\nNo"
NDA_STATUS = "Yes\nNo\nNot Required"
ORG_TYPE = "Government\nPrivate Sector\nPSU"
LEAD_SOURCE = "Tender Portal\nDirect Email\nExisting Client\nTrade Show\nOther"
EVAL_SUB = "Technical Bid Review\nPrice Bid Review\nCommercial Negotiation"
RANK = "L1\nL2\nL3\nN/A"
HANDOFF = "Pending Review\nLive"
DOC_CLASS = "Technical\nCommercial"


def _dep(stage: str) -> str:
	return f"eval:doc.sales_stage=='{stage}'"


def get_custom_fields() -> dict:
	cold = _dep(STAGE_COLD)
	inquiry = _dep(STAGE_INQUIRY)
	qual = _dep(STAGE_QUALIFICATION)
	queries = _dep(STAGE_QUERIES)
	proposal = _dep(STAGE_PROPOSAL)
	evaluation = _dep(STAGE_EVALUATION)
	closure = _dep(STAGE_CLOSURE)

	return {
		"Opportunity": _opportunity_fields(cold, inquiry, qual, queries, proposal, evaluation, closure),
		"Customer": _customer_fields(),
		"Project": _project_fields(),
		"File": _file_fields(),
	}


def _opportunity_fields(cold, inquiry, qual, queries, proposal, evaluation, closure):
	return [
		{
			"fieldname": "custom_pec_epc_tab",
			"label": "EPC Pipeline",
			"fieldtype": "Tab Break",
			"insert_after": "dashboard_tab",
			"module": MODULE,
		},
		{
			"fieldname": "custom_email_subject_tag",
			"label": "Email Subject Tag",
			"fieldtype": "Data",
			"read_only": 1,
			"insert_after": "custom_pec_epc_tab",
			"description": "Put this tag in email subjects so client replies attach to this Opportunity.",
			"module": MODULE,
		},
		{
			"fieldname": "custom_project",
			"label": "Handoff Project",
			"fieldtype": "Link",
			"options": "Project",
			"read_only": 1,
			"insert_after": "custom_email_subject_tag",
			"module": MODULE,
		},
		# Stage 1 Cold
		{
			"fieldname": "custom_stage_cold_section",
			"label": "Stage 1: Cold (Pre-Inquiry / Stalled)",
			"fieldtype": "Section Break",
			"insert_after": "custom_project",
			"depends_on": cold,
			"collapsible": 0,
			"module": MODULE,
		},
		{
			"fieldname": "custom_expected_tender_release_date",
			"label": "Expected Tender Release Date",
			"fieldtype": "Date",
			"insert_after": "custom_stage_cold_section",
			"depends_on": cold,
			"module": MODULE,
		},
		{
			"fieldname": "custom_cold_column",
			"fieldtype": "Column Break",
			"insert_after": "custom_expected_tender_release_date",
			"depends_on": cold,
			"module": MODULE,
		},
		{
			"fieldname": "custom_cold_market_segment",
			"label": "Market Segment / Application Type",
			"fieldtype": "Link",
			"options": "Market Segment",
			"insert_after": "custom_cold_column",
			"depends_on": cold,
			"description": "Also available on the main Opportunity form as Market Segment once the inquiry is logged.",
			"module": MODULE,
		},
		{
			"fieldname": "custom_cold_notes",
			"label": "Notes",
			"fieldtype": "Small Text",
			"insert_after": "custom_cold_market_segment",
			"depends_on": cold,
			"description": "Rumors, client discussions, or reason the lead stalled.",
			"module": MODULE,
		},
		# Stage 2 Inquiry
		{
			"fieldname": "custom_stage_inquiry_section",
			"label": "Stage 2: Inquiry / Tender",
			"fieldtype": "Section Break",
			"insert_after": "custom_cold_notes",
			"depends_on": inquiry,
			"module": MODULE,
		},
		{
			"fieldname": "custom_type_of_organization",
			"label": "Type of Organization",
			"fieldtype": "Select",
			"options": ORG_TYPE,
			"insert_after": "custom_stage_inquiry_section",
			"depends_on": inquiry,
			"mandatory_depends_on": inquiry,
			"module": MODULE,
		},
		{
			"fieldname": "custom_lead_source",
			"label": "Lead Source",
			"fieldtype": "Select",
			"options": LEAD_SOURCE,
			"insert_after": "custom_type_of_organization",
			"depends_on": inquiry,
			"mandatory_depends_on": inquiry,
			"module": MODULE,
		},
		{
			"fieldname": "custom_holding_company",
			"label": "Holding / Parent Company",
			"fieldtype": "Link",
			"options": "Customer",
			"insert_after": "custom_lead_source",
			"depends_on": inquiry,
			"module": MODULE,
		},
		{
			"fieldname": "custom_inquiry_column",
			"fieldtype": "Column Break",
			"insert_after": "custom_holding_company",
			"depends_on": inquiry,
			"module": MODULE,
		},
		{
			"fieldname": "custom_key_account",
			"label": "Key Account",
			"fieldtype": "Check",
			"insert_after": "custom_inquiry_column",
			"depends_on": inquiry,
			"description": "Flag high-priority existing clients.",
			"module": MODULE,
		},
		{
			"fieldname": "custom_referral_received_from",
			"label": "Referral Received From",
			"fieldtype": "Link",
			"options": "Contact",
			"insert_after": "custom_key_account",
			"depends_on": inquiry,
			"module": MODULE,
		},
		{
			"fieldname": "custom_wingman",
			"label": "WINGMAN",
			"fieldtype": "Link",
			"options": "User",
			"insert_after": "custom_referral_received_from",
			"depends_on": inquiry,
			"description": "Secondary support engineer or draftsman. Primary lead is Leading Deal Responsible (Opportunity Owner).",
			"module": MODULE,
		},
		{
			"fieldname": "custom_gate_inquiry_section",
			"label": "Gate to Qualification",
			"fieldtype": "Section Break",
			"insert_after": "custom_wingman",
			"depends_on": inquiry,
			"collapsible": 1,
			"module": MODULE,
		},
		{
			"fieldname": "custom_gate_inquiry_logged",
			"label": "Inquiry received, base details logged, and assigned to the estimation team",
			"fieldtype": "Check",
			"insert_after": "custom_gate_inquiry_section",
			"depends_on": inquiry,
			"module": MODULE,
		},
		# Stage 3 Qualification
		{
			"fieldname": "custom_stage_qualification_section",
			"label": "Stage 3: Qualification (Go / No-Go)",
			"fieldtype": "Section Break",
			"insert_after": "custom_gate_inquiry_logged",
			"depends_on": qual,
			"module": MODULE,
		},
		{
			"fieldname": "custom_tender_rfq_documents",
			"label": "Tender / RFQ Documents",
			"fieldtype": "Attach",
			"insert_after": "custom_stage_qualification_section",
			"depends_on": qual,
			"module": MODULE,
		},
		{
			"fieldname": "custom_bid_submission_deadline",
			"label": "Bid Submission Deadline",
			"fieldtype": "Datetime",
			"insert_after": "custom_tender_rfq_documents",
			"depends_on": qual,
			"module": MODULE,
		},
		{
			"fieldname": "custom_query_rfi_deadline",
			"label": "Query / RFI Deadline",
			"fieldtype": "Datetime",
			"insert_after": "custom_bid_submission_deadline",
			"depends_on": qual,
			"module": MODULE,
		},
		{
			"fieldname": "custom_qual_column",
			"fieldtype": "Column Break",
			"insert_after": "custom_query_rfi_deadline",
			"depends_on": qual,
			"module": MODULE,
		},
		{
			"fieldname": "custom_nda_status",
			"label": "NDA Status",
			"fieldtype": "Select",
			"options": NDA_STATUS,
			"insert_after": "custom_qual_column",
			"depends_on": qual,
			"module": MODULE,
		},
		{
			"fieldname": "custom_nda_attachment",
			"label": "NDA Attachment",
			"fieldtype": "Attach",
			"insert_after": "custom_nda_status",
			"depends_on": qual,
			"module": MODULE,
		},
		{
			"fieldname": "custom_study_metrics_section",
			"label": "Technical & Commercial Study",
			"fieldtype": "Section Break",
			"insert_after": "custom_nda_attachment",
			"depends_on": qual,
			"module": MODULE,
		},
		{
			"fieldname": "custom_location_feasibility",
			"label": "Location Feasibility",
			"fieldtype": "Select",
			"options": YES_NO_REVIEW,
			"insert_after": "custom_study_metrics_section",
			"depends_on": qual,
			"module": MODULE,
		},
		{
			"fieldname": "custom_budget_finance",
			"label": "Budget & Finance",
			"fieldtype": "Select",
			"options": YES_NO_REVIEW,
			"insert_after": "custom_location_feasibility",
			"depends_on": qual,
			"module": MODULE,
		},
		{
			"fieldname": "custom_authority",
			"label": "Authority",
			"fieldtype": "Select",
			"options": YES_NO_REVIEW,
			"insert_after": "custom_budget_finance",
			"depends_on": qual,
			"description": "Are we dealing with core procurement/engineering decision-makers?",
			"module": MODULE,
		},
		{
			"fieldname": "custom_study_column",
			"fieldtype": "Column Break",
			"insert_after": "custom_authority",
			"depends_on": qual,
			"module": MODULE,
		},
		{
			"fieldname": "custom_timeline_feasibility",
			"label": "Timeline Feasibility",
			"fieldtype": "Select",
			"options": YES_NO_REVIEW,
			"insert_after": "custom_study_column",
			"depends_on": qual,
			"module": MODULE,
		},
		{
			"fieldname": "custom_complexity_scope",
			"label": "Complexity & Scope (Bandwidth)",
			"fieldtype": "Select",
			"options": YES_NO_REVIEW,
			"insert_after": "custom_timeline_feasibility",
			"depends_on": qual,
			"module": MODULE,
		},
		{
			"fieldname": "custom_subcontract_required",
			"label": "Subcontract Required",
			"fieldtype": "Select",
			"options": YES_NO,
			"insert_after": "custom_complexity_scope",
			"depends_on": qual,
			"module": MODULE,
		},
		{
			"fieldname": "custom_subcontracted_scope",
			"label": "Subcontracted Scope",
			"fieldtype": "Small Text",
			"insert_after": "custom_subcontract_required",
			"depends_on": f"eval:doc.sales_stage=='{STAGE_QUALIFICATION}' && doc.custom_subcontract_required=='Yes'",
			"mandatory_depends_on": f"eval:doc.sales_stage=='{STAGE_QUALIFICATION}' && doc.custom_subcontract_required=='Yes'",
			"module": MODULE,
		},
		{
			"fieldname": "custom_gate_qual_section",
			"label": "Gate to Queries & Clarifications",
			"fieldtype": "Section Break",
			"insert_after": "custom_subcontracted_scope",
			"depends_on": qual,
			"collapsible": 1,
			"module": MODULE,
		},
		{
			"fieldname": "custom_gate_docs_uploaded",
			"label": "All initial tender documents and RFQ emails are uploaded",
			"fieldtype": "Check",
			"insert_after": "custom_gate_qual_section",
			"depends_on": qual,
			"module": MODULE,
		},
		{
			"fieldname": "custom_gate_deadline_logged",
			"label": "Bid submission deadline is confirmed and logged",
			"fieldtype": "Check",
			"insert_after": "custom_gate_docs_uploaded",
			"depends_on": qual,
			"module": MODULE,
		},
		{
			"fieldname": "custom_qualified_go_nogo",
			"label": "Are we qualified to do this job? (Go / No-Go)",
			"fieldtype": "Select",
			"options": YES_NO,
			"insert_after": "custom_gate_deadline_logged",
			"depends_on": qual,
			"description": "Yes advances the bid. No requires marking the Opportunity as Lost in this stage.",
			"module": MODULE,
		},
		# Stage 4 Queries
		{
			"fieldname": "custom_stage_queries_section",
			"label": "Stage 4: Queries & Clarifications",
			"fieldtype": "Section Break",
			"insert_after": "custom_qualified_go_nogo",
			"depends_on": queries,
			"module": MODULE,
		},
		{
			"fieldname": "custom_pre_bid_meeting_date",
			"label": "Pre-Bid Meeting Date",
			"fieldtype": "Date",
			"insert_after": "custom_stage_queries_section",
			"depends_on": queries,
			"module": MODULE,
		},
		{
			"fieldname": "custom_queries_column",
			"fieldtype": "Column Break",
			"insert_after": "custom_pre_bid_meeting_date",
			"depends_on": queries,
			"module": MODULE,
		},
		{
			"fieldname": "custom_clarifications_addendums",
			"label": "Clarifications & Addendums",
			"fieldtype": "Attach",
			"insert_after": "custom_queries_column",
			"depends_on": queries,
			"module": MODULE,
		},
		{
			"fieldname": "custom_gate_queries_section",
			"label": "Gate to Proposal Submitted",
			"fieldtype": "Section Break",
			"insert_after": "custom_clarifications_addendums",
			"depends_on": queries,
			"collapsible": 1,
			"module": MODULE,
		},
		{
			"fieldname": "custom_gate_queries_clarified",
			"label": "All technical queries have been clarified by the client",
			"fieldtype": "Check",
			"insert_after": "custom_gate_queries_section",
			"depends_on": queries,
			"module": MODULE,
		},
		{
			"fieldname": "custom_gate_scope_locked",
			"label": "Final scope of work is locked for estimation",
			"fieldtype": "Check",
			"insert_after": "custom_gate_queries_clarified",
			"depends_on": queries,
			"module": MODULE,
		},
		# Stage 5 Proposal
		{
			"fieldname": "custom_stage_proposal_section",
			"label": "Stage 5: Proposal Submitted",
			"fieldtype": "Section Break",
			"insert_after": "custom_gate_scope_locked",
			"depends_on": proposal,
			"module": MODULE,
		},
		{
			"fieldname": "custom_submitted_bid_value",
			"label": "Submitted Bid Value",
			"fieldtype": "Currency",
			"options": "currency",
			"insert_after": "custom_stage_proposal_section",
			"depends_on": proposal,
			"module": MODULE,
		},
		{
			"fieldname": "custom_bid_validity_expiry_date",
			"label": "Bid Validity Expiry Date",
			"fieldtype": "Date",
			"insert_after": "custom_submitted_bid_value",
			"depends_on": proposal,
			"description": "The system emails the deal owner 7 days before this date.",
			"module": MODULE,
		},
		{
			"fieldname": "custom_proposal_column",
			"fieldtype": "Column Break",
			"insert_after": "custom_bid_validity_expiry_date",
			"depends_on": proposal,
			"module": MODULE,
		},
		{
			"fieldname": "custom_final_proposal_upload",
			"label": "Final Proposal Upload",
			"fieldtype": "Attach",
			"insert_after": "custom_proposal_column",
			"depends_on": proposal,
			"description": "Commercial offer — not copied to the Project workspace.",
			"module": MODULE,
		},
		{
			"fieldname": "custom_gate_proposal_section",
			"label": "Gate to Evaluation",
			"fieldtype": "Section Break",
			"insert_after": "custom_final_proposal_upload",
			"depends_on": proposal,
			"collapsible": 1,
			"module": MODULE,
		},
		{
			"fieldname": "custom_gate_proposal_sent",
			"label": "Proposal has been officially sent / uploaded to the portal",
			"fieldtype": "Check",
			"insert_after": "custom_gate_proposal_section",
			"depends_on": proposal,
			"module": MODULE,
		},
		{
			"fieldname": "custom_gate_emd_submitted",
			"label": "EMD / Bid Security submitted (if applicable)",
			"fieldtype": "Check",
			"insert_after": "custom_gate_proposal_sent",
			"depends_on": proposal,
			"module": MODULE,
		},
		# Stage 6 Evaluation
		{
			"fieldname": "custom_stage_evaluation_section",
			"label": "Stage 6: Evaluation",
			"fieldtype": "Section Break",
			"insert_after": "custom_gate_emd_submitted",
			"depends_on": evaluation,
			"module": MODULE,
		},
		{
			"fieldname": "custom_evaluation_sub_stage",
			"label": "Sub-Stage Status",
			"fieldtype": "Select",
			"options": EVAL_SUB,
			"insert_after": "custom_stage_evaluation_section",
			"depends_on": evaluation,
			"mandatory_depends_on": evaluation,
			"module": MODULE,
		},
		{
			"fieldname": "custom_eval_column",
			"fieldtype": "Column Break",
			"insert_after": "custom_evaluation_sub_stage",
			"depends_on": evaluation,
			"module": MODULE,
		},
		{
			"fieldname": "custom_commercial_rank",
			"label": "Our Commercial Rank",
			"fieldtype": "Select",
			"options": RANK,
			"insert_after": "custom_eval_column",
			"depends_on": f"eval:doc.sales_stage=='{STAGE_EVALUATION}' && doc.custom_evaluation_sub_stage=='Price Bid Review'",
			"module": MODULE,
		},
		{
			"fieldname": "custom_gate_eval_section",
			"label": "Gate to Closure (Won)",
			"fieldtype": "Section Break",
			"insert_after": "custom_commercial_rank",
			"depends_on": evaluation,
			"collapsible": 1,
			"module": MODULE,
		},
		{
			"fieldname": "custom_gate_loi_po_received",
			"label": "Client has issued a formal LOI or Purchase Order",
			"fieldtype": "Check",
			"insert_after": "custom_gate_eval_section",
			"depends_on": evaluation,
			"module": MODULE,
		},
		# Stage 7 Closure
		{
			"fieldname": "custom_stage_closure_section",
			"label": "Stage 7: Closure (Won)",
			"fieldtype": "Section Break",
			"insert_after": "custom_gate_loi_po_received",
			"depends_on": closure,
			"module": MODULE,
		},
		{
			"fieldname": "custom_final_negotiated_contract_value",
			"label": "Final Negotiated Contract Value",
			"fieldtype": "Currency",
			"options": "currency",
			"insert_after": "custom_stage_closure_section",
			"depends_on": closure,
			"mandatory_depends_on": closure,
			"module": MODULE,
		},
		{
			"fieldname": "custom_expected_project_start_date",
			"label": "Expected Project Start Date",
			"fieldtype": "Date",
			"insert_after": "custom_final_negotiated_contract_value",
			"depends_on": closure,
			"mandatory_depends_on": closure,
			"module": MODULE,
		},
		{
			"fieldname": "custom_closure_column",
			"fieldtype": "Column Break",
			"insert_after": "custom_expected_project_start_date",
			"depends_on": closure,
			"module": MODULE,
		},
		{
			"fieldname": "custom_expected_project_end_date",
			"label": "Expected Project End Date",
			"fieldtype": "Date",
			"insert_after": "custom_closure_column",
			"depends_on": closure,
			"mandatory_depends_on": closure,
			"module": MODULE,
		},
		{
			"fieldname": "custom_work_order_po_upload",
			"label": "Work Order / Client PO",
			"fieldtype": "Attach",
			"insert_after": "custom_expected_project_end_date",
			"depends_on": closure,
			"description": "Commercial award document. Stays on the Opportunity; not copied to Project.",
			"module": MODULE,
		},
	]


def _customer_fields():
	return [
		{
			"fieldname": "custom_bid_intelligence_tab",
			"label": "Bid Intelligence",
			"fieldtype": "Tab Break",
			"insert_after": "connections_tab",
			"module": MODULE,
		},
		{
			"fieldname": "custom_total_inquiries",
			"label": "Total Inquiries / Projects Received",
			"fieldtype": "Int",
			"read_only": 1,
			"insert_after": "custom_bid_intelligence_tab",
			"module": MODULE,
		},
		{
			"fieldname": "custom_projects_won",
			"label": "Total Projects Won",
			"fieldtype": "Int",
			"read_only": 1,
			"insert_after": "custom_total_inquiries",
			"module": MODULE,
		},
		{
			"fieldname": "custom_kpi_column",
			"fieldtype": "Column Break",
			"insert_after": "custom_projects_won",
			"module": MODULE,
		},
		{
			"fieldname": "custom_projects_lost",
			"label": "Total Projects Lost",
			"fieldtype": "Int",
			"read_only": 1,
			"insert_after": "custom_kpi_column",
			"module": MODULE,
		},
		{
			"fieldname": "custom_projects_cold",
			"label": "Total Projects Cold",
			"fieldtype": "Int",
			"read_only": 1,
			"insert_after": "custom_projects_lost",
			"module": MODULE,
		},
		{
			"fieldname": "custom_active_bids",
			"label": "Total Active Bids",
			"fieldtype": "Int",
			"read_only": 1,
			"insert_after": "custom_projects_cold",
			"module": MODULE,
		},
		{
			"fieldname": "custom_account_intelligence_html",
			"label": "Account Summary",
			"fieldtype": "HTML",
			"insert_after": "custom_active_bids",
			"module": MODULE,
		},
	]


def _project_fields():
	return [
		{
			"fieldname": "custom_opportunity",
			"label": "Source Opportunity",
			"fieldtype": "Link",
			"options": "Opportunity",
			"insert_after": "sales_order",
			"read_only": 1,
			"module": MODULE,
		},
		{
			"fieldname": "custom_handoff_status",
			"label": "Handoff Status",
			"fieldtype": "Select",
			"options": HANDOFF,
			"default": "Pending Review",
			"insert_after": "status",
			"description": "Pending Review is the Draft gate. A manager must set Live before execution treats the project as released.",
			"module": MODULE,
		},
		{
			"fieldname": "custom_contract_value",
			"label": "Negotiated Contract Value",
			"fieldtype": "Currency",
			"insert_after": "estimated_costing",
			"module": MODULE,
		},
	]


def _file_fields():
	return [
		{
			"fieldname": "custom_document_class",
			"label": "PEC Document Class",
			"fieldtype": "Select",
			"options": DOC_CLASS,
			"insert_after": "attached_to_field",
			"description": "Technical files copy to Project. Commercial files stay on the Opportunity.",
			"module": MODULE,
		},
	]
